version: '3'
services:
  jarm_online_gui:
    build: jarm_online_gui/.
    image: jarm_online_gui
    container_name: jarm_online_gui_container
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - jarm_online_api

  jarm_online_api:
    build: .
    image: jarm_online_api
    container_name: jarm_online_api
    stop_signal: SIGKILL  # SIGTERM is allowed in config starting with rocket.rs 0.5
    restart: unless-stopped
    ports:
      - "8000:8000"
