version: '3.8'
services:
  jarm_online_gui:
    build:
      context: jarm_online_gui/.
      args:
        VUE_APP_SENTRY_DSN: $VUE_APP_SENTRY_DSN
    image: jarm_online_gui
    container_name: jarm_online_gui_container
    ports:
      - "80:80"

  jarm_online_api:
    build: .
    image: jarm_online_api
    container_name: jarm_online_api_container
    environment:
      - ROCKET_PROFILE=release
      - ROCKET_DATABASES={redis_db={url="redis://redis"}}
      - ROCKET_SENTRY_DSN=${ROCKET_SENTRY_DSN:-https://123@deactivated.io/123}
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine
    container_name: jarm_online_redis_container
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
