services:
  jarm_online_gui:
    extends:
      file: docker-compose.yml
      service: jarm_online_gui
    ports:
      - "80:80"
    depends_on:
      - jarm_online_api
      - playwright_dummy_server

  jarm_online_api:
    extends:
      file: docker-compose.yml
      service: jarm_online_api
    environment:
      - ROCKET_SENTRY_DSN=123  # this way sentry is disabled but do not crash
      - FORCE_TRANCO_TOP1M_RAW_DATA_PATH=/tranco_top1M.csv
    volumes:
      - ./tests/fixtures_data/tranco_top1M.csv:/tranco_top1M.csv
    depends_on:
      - redis

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  playwright_dummy_server:
    container_name: playwright_dummy_server_container
    image: hugocker/nginx_tls_dummy_server:latest
    ports:
      - "443:443"

  pytest_runner:
    image: hugocker/playwright_runner
    environment:
      - PLAYWRIGHT_URL_UNDER_TEST=http://jarm_online_gui/
    volumes:
      - ./tests:/code/tests
    depends_on:
      - playwright_dummy_server
      - jarm_online_gui