[default]
port = 8000
log_level = "normal"

[debug]
address = "127.0.0.1"
workers = 2

[release]
address = "0.0.0.0"

[default.databases.redis_db]
url = "redis://localhost"

[default.databases.sqlite_db]
url = "sqlite_data/db.sqlite"