---
- hosts: localhost
  become: true
  vars:
    project_dir: "/srv/opt/jarm_online"

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - bridge-utils
          - ca-certificates
          - curl
          - git
          - gnupg
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: get architecture
      shell: dpkg --print-architecture
      register: deb_architecture



    - name: get gpg key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644
        force: true
      tags: install_docker

    - name: add docker apt repository key.
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: 0644
        force: true
      tags: install_docker

    - name: add docker apt repository.
      apt_repository:
        repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
        filename: docker
      tags: install_docker

    - name: install docker and related components
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
      tags: install_docker

    - name: restart Docker
      systemd:
        name: docker
        state: restarted
        masked: no
      tags: install_docker

    - name: Clone repo
      ansible.builtin.git:
        repo: https://github.com/Hugo-C/jarm-online.git
        dest: /git/jarm-online
        single_branch: true
        version: master
        update: true
        depth: 1

    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory

    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: /git/jarm-online/docker-compose.yml.prod  # we use the production one
        dest: "{{ project_dir }}/docker-compose.yml"
        force: false  # don't overwrite files

    - name: Create nginx directory
      file:
        path: "{{ project_dir }}/nginx"
        state: directory

    - name: Create nginx logs directory
      file:
        path: "{{ project_dir }}/nginx_logs"
        state: directory

    - name: Copy nginx conf
      ansible.builtin.copy:
        src: /git/jarm-online/jarm_online_gui/nginx.conf.prod
        dest: "{{ project_dir }}/nginx/nginx.conf"
        force: false  # don't overwrite files

    - name: Check that cert file exist
      stat:
        path: "{{ project_dir }}/nginx/www.hugocjarm.software.pem"
      register: cert_result

    - name: Remind cert file has to be manually set
      fail:
        msg: "Warning: {{ project_dir }}/nginx/www.hugocjarm.software.pem and its key has to be manually set"
      when: not cert_result.stat.exists
      ignore_errors: True

    - name: Check that .env file exist
      stat:
        path: "{{ project_dir }}/.env"
      register: env_result

    - name: Remind .env file has to be manually set
      fail:
        msg: "Warning: {{ project_dir }}/.env has to be manually set"
      when: not env_result.stat.exists

    - name: Start containers
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        pull: always

    - name: Add logrotate to nginx
      ansible.builtin.copy:
        src: /git/jarm-online/nginx_log_rotate
        dest: "/etc/logrotate.d/nginx"
        force: true